# Generated by Django 4.2.9 on 2024-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_product_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoUrl',
            field=models.TextField(default='src'),
        ),
    ]
